# Generated by Django 3.2.8 on 2021-10-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('IdEspecie', models.AutoField(primary_key=True, serialize=False)),
                ('NombreEspecie', models.CharField(max_length=250)),
                ('EstadoEspecie', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FamiliaDeOrquideas',
            fields=[
                ('IdFamiliaDeOrquideas', models.AutoField(primary_key=True, serialize=False)),
                ('NombreFamiliaDeOrquideas', models.CharField(max_length=250)),
                ('EstadoFamiliaDeOrquideas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('IdGenero', models.AutoField(primary_key=True, serialize=False)),
                ('NombreGenero', models.CharField(max_length=250)),
                ('EstadoGenero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orquidea',
            fields=[
                ('idOrquidea', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_crecimiento', models.CharField(max_length=30)),
                ('nombre_comun', models.CharField(max_length=30, unique=True)),
                ('floracion', models.CharField(max_length=30)),
                ('duracion_flor', models.CharField(max_length=30)),
                ('tamaño_flor', models.CharField(max_length=30)),
                ('ubicacion', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('IdUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('EmailUsuario', models.CharField(max_length=250)),
                ('PasswordUsuario', models.CharField(max_length=20)),
                ('EstadoUsuario', models.IntegerField()),
            ],
        ),
    ]
